# Generated by Django 6.0.2 on 2026-02-12 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_remove_order_ordered_remove_order_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="class_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("elegant", "Elegant"),
                    ("bold", "Bold"),
                    ("royal", "Royal"),
                    ("modern", "Modern Chic"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="fashion_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("casual", "Casual"),
                    ("street", "Street Style"),
                    ("luxury", "Luxury"),
                    ("minimal", "Minimal"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="skin_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("oily", "Oily"),
                    ("dry", "Dry"),
                    ("combination", "Combination"),
                    ("sensitive", "Sensitive"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
