# Generated by Django 6.0.2 on 2026-02-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0008_order_status_alter_order_total_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Processing", "Processing"),
                    ("Shipped", "Shipped"),
                    ("Out for Delivery", "Out for Delivery"),
                    ("Delivered", "Delivered"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=30,
            ),
        ),
    ]
