# Generated by Django 6.0.2 on 2026-03-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0009_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="collection",
            field=models.CharField(
                blank=True,
                choices=[
                    ("kbeauty", "K-Beauty"),
                    ("genz", "Gen Z"),
                    ("wedding", "Wedding"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
