# Generated by Django 6.0.2 on 2026-03-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0010_product_collection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="collection",
            field=models.CharField(
                blank=True,
                choices=[
                    ("kbeauty", "K-Beauty"),
                    ("genz", "Gen Z"),
                    ("wedding", "Wedding"),
                    ("everyday", "Everyday Beauty"),
                    ("festive", "Festive Glow"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
