# Generated by Django 6.0.2 on 2026-06-22 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_image',
            field=models.ImageField(blank=True, null=True, upload_to='reviews/'),
        ),
    ]
